services:
  php:
    build:
      context: ./docker/php
    container_name: mrapi-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - couchdb
    networks: [appnet]

  nginx:
    image: nginx:1.27-alpine
    container_name: mrapi-nginx
    ports:
      - "9000:80"             # http://localhost:9000
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks: [appnet]

  couchdb:
    image: couchdb:3
    container_name: mrapi-couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin123
    ports:
      - "5984:5984"           # Fauxton: http://localhost:5984/_utils/
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks: [appnet]

  # (Tùy chọn) MailHog phục vụ test mail (nếu không dùng Gmail)
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mrapi-mailhog
    ports:
      - "1025:1025"           # SMTP
      - "8025:8025"           # UI http://localhost:8025
    networks: [appnet]

volumes:
  couchdb_data:

networks:
  appnet:
    driver: bridge
