name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      couchdb:
        image: couchdb:3
        ports:
          - 5984:5984
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: admin123
        options: >-
          --health-cmd="curl -f http://localhost:5984/_up || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, zip, gd, bcmath, curl
          coverage: none
          tools: composer:v2

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      # Thay step "Prepare .env (CI)" trong .github/workflows/ci.yml bằng:
      - name: Prepare .env (CI)
        run: |
          rm -f .env
          cat > .env <<'EOF'
          APP_NAME="Medical Records API"
          APP_ENV=testing
          APP_DEBUG=true
          APP_URL=http://localhost:9000
          APP_KEY=
          LOG_CHANNEL=stack

          # CouchDB service trong CI dùng localhost
          COUCHDB_HOST=localhost
          COUCHDB_PORT=5984
          COUCHDB_USERNAME="admin"
          COUCHDB_PASSWORD="admin123"

          # Để CI chạy không cần DB quan hệ
          QUEUE_CONNECTION=sync
          CACHE_DRIVER=array
          SESSION_DRIVER=array
          BROADCAST_DRIVER=log
          MAIL_MAILER=log
          EOF

          php -r "file_put_contents('.env', preg_replace('/^APP_KEY=.*/m','APP_KEY='.('base64:'.base64_encode(random_bytes(32))), file_get_contents('.env')));"
          php artisan config:clear

      - name: Run Pint (report only, non-blocking)
        continue-on-error: true
        run: |
          if [ -f vendor/bin/pint ]; then
            vendor/bin/pint --test || echo "::warning::Pint found style issues (non-blocking)."
          else
            echo "No Pint installed, skipping."
          fi

      - name: PHPUnit
        run: |
          if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit --colors=always; else echo "No phpunit found, skipping"; fi

      - name: Generate Swagger (non-blocking)
        continue-on-error: true
        run: |
          if [ -f artisan ]; then php artisan l5-swagger:generate; fi
