name: CI
on:
  push: { branches: [ main, develop ] }
  pull_request: { branches: [ main, develop ] }

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      couchdb:
        image: couchdb:3
        ports: [ "5984:5984" ]
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: admin123
        options: >-
          --health-cmd="curl -fsS http://localhost:5984/_up || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=40

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, zip, gd, bcmath, curl
          tools: composer:v2
          coverage: none

      - uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      # 1) CHUẨN BỊ .env trước (đừng copy .env.example để tránh ${...})
      - name: Prepare .env (CI)
        run: |
          rm -f .env
          cat > .env <<'EOF'
          APP_NAME="Medical Records API"
          APP_ENV=testing
          APP_DEBUG=true
          APP_URL=http://localhost:9000
          APP_KEY=
          LOG_CHANNEL=stack

          COUCHDB_HOST=localhost
          COUCHDB_PORT=5984
          COUCHDB_USERNAME="admin"
          COUCHDB_PASSWORD="admin123"

          QUEUE_CONNECTION=sync
          CACHE_DRIVER=array
          SESSION_DRIVER=array
          BROADCAST_DRIVER=log
          MAIL_MAILER=log
          EOF
          php -r "file_put_contents('.env', preg_replace('/^APP_KEY=.*/m','APP_KEY='.('base64:'.base64_encode(random_bytes(32))), file_get_contents('.env')));"

      # 2) Đợi CouchDB thực sự up + set n=1 + tạo DB hệ thống
      - name: Wait & init CouchDB
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:5984/_up >/dev/null; then
              echo "CouchDB is up"; break
            fi; sleep 1
          done
          curl -fsS -u admin:admin123 -X PUT http://localhost:5984/_node/_local/_config/cluster/n -d '"1"'
          for db in _users _replicator _global_changes; do
            curl -fsS -u admin:admin123 -X PUT "http://localhost:5984/$db?n=1" || true
          done

      # 3) CÀI composer SAU khi .env và CouchDB sẵn sàng
      #    (nếu vẫn cẩn thận: dùng --no-scripts rồi artisan phía dưới)
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Clear config/cache (safe)
        run: |
          php artisan config:clear || true
          php artisan cache:clear || true

      # 4) Pint non-blocking
      - name: Run Pint (non-blocking, quiet)
        continue-on-error: true
        run: |
          if [ -f vendor/bin/pint ]; then
            vendor/bin/pint --test -q || echo "::warning::Pint found style issues (non-blocking)."
          fi

      # 5) PHPUnit skip nếu không có tests
      - name: PHPUnit (skip if none)
        run: |
          if [ -d tests ] && [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit --colors=always
          else
            echo "No tests folder, skipping."
          fi

      # 6) Swagger non-blocking (và chỉ chạy khi có package)
      - name: Generate Swagger (non-blocking, only if installed)
        continue-on-error: true
        run: |
          if [ -f artisan ] && php -r "exit((int)!class_exists('L5Swagger\\L5SwaggerServiceProvider'));" ; then
            php artisan l5-swagger:generate || echo "Swagger failed (non-blocking)"
          else
            echo "L5-Swagger not installed or artisan missing, skipping."
          fi
