name: CI - Laravel Tests

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      couchdb:
        image: couchdb:3
        ports:
          - 5984:5984
        env:
          COUCHDB_USER: ${{ secrets.COUCHDB_USER }}
          COUCHDB_PASSWORD: ${{ secrets.COUCHDB_PASSWORD }}
          COUCHDB_SINGLE_NODE: "true"   # ← auto tạo system DBs, đỡ phải curl PUT
        options: >-
          --health-cmd "curl -fsS http://localhost:5984/_up || exit 1"
          --health-interval 2s
          --health-timeout 2s
          --health-retries 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, json, pdo, bcmath
          coverage: none

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist

      - name: Prepare .env for tests
        shell: bash
        run: |
          set -euo pipefail
          cp .env.example .env 2>/dev/null || true

          # APP_KEY: ưu tiên secrets, nếu thiếu thì generate
          if [[ -n "${{ secrets.APP_KEY }}" ]]; then
            if grep -q '^APP_KEY=' .env; then
              sed -i "s|^APP_KEY=.*|APP_KEY=${{ secrets.APP_KEY }}|" .env
            else
              echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
            fi
          else
            php artisan key:generate --force --ansi
          fi

          # Biến môi trường test (không có mail)
          cat >> .env <<'ENV'
          APP_ENV=testing
          APP_DEBUG=true
          APP_URL=http://localhost:9000
          COUCHDB_HOST=127.0.0.1
          COUCHDB_PORT=5984
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120
          SANCTUM_STATEFUL_DOMAINS=localhost,localhost:4200,localhost:9000
          SESSION_DOMAIN=localhost
          ENV

          # Bổ sung secrets/vars nếu có
          [[ -n "${{ secrets.COUCHDB_USER }}" ]]     && printf "COUCHDB_USERNAME=%s\n" "${{ secrets.COUCHDB_USER }}"     >> .env
          [[ -n "${{ secrets.COUCHDB_PASSWORD }}" ]] && printf "COUCHDB_PASSWORD=%s\n" "${{ secrets.COUCHDB_PASSWORD }}" >> .env
          [[ -n "${{ secrets.JWT_SECRET }}" ]]       && printf "JWT_SECRET=%s\n"       "${{ secrets.JWT_SECRET }}"       >> .env

          cp .env .env.testing || true
          php artisan config:clear

      - name: Wait for CouchDB
        run: |
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:5984/_up >/dev/null; then
              echo "CouchDB is up"; break
            fi
            sleep 1
          done

      - name: Run PHPUnit
        run: |
          if [ -f vendor/bin/phpunit ] && git ls-files "tests/**/*.php" | grep -q .; then
            vendor/bin/phpunit --colors=always
          else
            echo "No test files, skipping."
          fi
