name: Deploy via SSH

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copy files (optional)
        run: |
          rsync -az --delete -e "ssh -p ${{ secrets.SSH_PORT }}" \
            . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/medical-records-api

      - name: Remote deploy
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          cd /var/www/medical-records-api
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin || true
          docker compose pull
          docker compose up -d
          docker system prune -f
          EOF
